In [9]:
import numpy as np
import pandas as pd

In [10]:
df=pd.read_csv("resultsTable.txt",sep=' ')

In [11]:
df

    beta      q        x1        x2        x3       Var      Cvar
0   0.90   1000  0.313049  0.165307  0.521644  0.063062  0.094807
1   0.90   3000  0.419921  0.122974  0.457106  0.064191  0.093045
2   0.90   5000  0.468433  0.103758  0.427810  0.070526  0.099258
3   0.90  10000  0.420770  0.122637  0.456592  0.068024  0.097253
4   0.90  20000  0.405869  0.128540  0.465591  0.068102  0.096490
5   0.95   1000  0.445560  0.112818  0.441622  0.090979  0.114206
6   0.95   2000  0.361934  0.145943  0.492123  0.087965  0.113116
7   0.95   3000  0.356371  0.148146  0.495482  0.093990  0.119796
8   0.95   5000  0.384653  0.136944  0.478403  0.089157  0.114562
9   0.95  10000  0.308896  0.166952  0.524152  0.091168  0.118805
10  0.95  20000  0.355270  0.148583  0.496147  0.089720  0.114607
11  0.99   1000  0.393467  0.133453  0.473081  0.119341  0.131075
12  0.99   3000  0.542996  0.074222  0.382782  0.139283  0.156592
13  0.99   5000  0.394506  0.133041  0.472453  0.141016  0.163303
14  0.99  10000  0.309204  0.166830  0.523966  0.138074  0.159812
15  0.99  20000  0.334413  0.156844  0.508743  0.132687  0.154187